package com.mobatrade.core.engine

import com.mobatrade.core.auth.TotpGenerator
import com.mobatrade.core.halal.ShariahFilter
import com.mobatrade.core.halal.ZoyaSyncService
import com.mobatrade.core.model.Direction
import com.mobatrade.core.model.Order
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.io.File

class ZoyaSyncTest {

    private val testCachePath = "c:\\moba trade\\test_halal_stocks.json"

    @BeforeEach
    fun setUp() {
        // Ensure clean test state
        val testFile = File(testCachePath)
        if (testFile.exists()) {
            testFile.delete()
        }
    }

    @Test
    fun testTotpGenerationFormat() {
        val secret = "133ea263-b945-47a1-a718-9d063fecd674"
        val code = TotpGenerator.generateTOTP(secret)
        
        assertNotNull(code)
        assertEquals(6, code.length, "TOTP must be exactly 6 digits")
        assertTrue(code.all { it.isDigit() }, "TOTP must contain only numeric digits")
    }

    @Test
    fun testTotpGenerationMatching() {
        val secret = "K336YHYAV6NN5H2DYMPBBZ55NM"
        // timeStep = 59350845 (at 1780525350 epoch seconds)
        val code = TotpGenerator.generateTOTP(secret, 1780525350L)
        assertEquals("070999", code, "TOTP code generated by server must match standard value")
    }

    @Test
    fun testZoyaSyncAndLocalCaching() {
        val testStocks = listOf(
            ZoyaSyncService.CompliantStock("TCS", "Tata Consultancy Services Ltd", "NSE", 0.05),
            ZoyaSyncService.CompliantStock("INFY", "Infosys Ltd", "NSE", 0.03),
            ZoyaSyncService.CompliantStock("WIPRO", "Wipro Ltd", "NSE", 0.02)
        )

        // Verify cache writing
        val success = ZoyaSyncService.saveCompliantUniverseToCache(testStocks, testCachePath)
        assertTrue(success, "Should save compliant stocks successfully to the local JSON cache")

        val testFile = File(testCachePath)
        assertTrue(testFile.exists(), "Cache file must exist on disk after saving")

        // Load the cached universe into ShariahFilter
        val loadSuccess = ShariahFilter.loadUniverse(testCachePath)
        assertTrue(loadSuccess, "Should load cached compliant universe successfully")
        
        assertEquals(3, ShariahFilter.size(), "Shariah filter should index exactly 3 stocks")
        assertTrue(ShariahFilter.isCompliantSymbol("TCS"), "TCS must be recognized as compliant")
        assertTrue(ShariahFilter.isCompliantSymbol("INFY"), "INFY must be recognized as compliant")
        assertFalse(ShariahFilter.isCompliantSymbol("RELIANCE"), "RELIANCE must NOT be recognized as compliant")

        // Clean up
        testFile.delete()
    }

    @Test
    fun testAngelOneShariahOrderGuard() {
        // Manually initialize Shariah Filter with a limited compliant universe
        ShariahFilter.initializeManual(
            symbols = listOf("TCS", "INFY"),
            tokens = listOf("11536", "1594")
        )

        // 1. Compliant Order - Should Proceed to API Authentication block (fails login since we use default mock credentials in unit environment)
        val halalOrder = Order("TCS", 5, 3100.0, Direction.BUY, "MARKET")
        val halalResult = AngelOneClient.placeOrder(halalOrder, "11536")
        
        // Since we're not logged in, it should return null but the log must show it passed the Shariah compliance check.
        assertNull(halalResult, "Order should fail because the session is not authenticated, not due to Shariah blocking")

        // 2. Non-Compliant Order - Should be BLOCKED immediately at Shariah guard
        val haramOrder = Order("RELIANCE", 10, 2400.0, Direction.BUY, "MARKET")
        val haramResult = AngelOneClient.placeOrder(haramOrder, "99999")
        
        assertNull(haramResult, "Non-compliant order must be blocked and return null immediately")
        
        // 3. Short Selling Order - Should be BLOCKED immediately
        val shortOrder = Order("TCS", -5, 3100.0, Direction.SELL, "MARKET")
        val shortResult = AngelOneClient.placeOrder(shortOrder, "11536")
        
        assertNull(shortResult, "Short-selling order must be blocked by Shariah rules")

        // 4. Non-Compliant SELL Order (Liquidation) - Should NOT be blocked by Shariah guard (proceeds to auth check)
        val sellNonCompliantOrder = Order("RELIANCE", 10, 2400.0, Direction.SELL, "MARKET")
        val sellNonCompliantResult = AngelOneClient.placeOrder(sellNonCompliantOrder, "99999")
        
        assertNull(sellNonCompliantResult, "Order should fail because the session is not authenticated, not due to Shariah blocking")
    }

    @Test
    fun testHistoricalCandleTimeParsing() {
        val timestampStr = "2026-06-01T09:15:00+05:30"
        val parsed = java.time.OffsetDateTime.parse(timestampStr)
        assertNotNull(parsed)
        assertEquals(2026, parsed.year)
        assertEquals(6, parsed.monthValue)
        assertEquals(1, parsed.dayOfMonth)
        assertEquals(9, parsed.hour)
        assertEquals(15, parsed.minute)
        
        val instant = parsed.toInstant()
        assertNotNull(instant)
    }

    @Test
    fun testFetchHistoricalCandlesUnauthenticated() {
        // Ensure we are logged out and auto-login fails by using an invalid client ID
        AngelOneClient.logout()
        val originalClientId = AngelOneClient.activeClientId
        AngelOneClient.login(clientId = "INVALID_CLIENT")
        AngelOneClient.logout() // clear token set by login if any (though it would have failed)
        
        AngelOneClient.autoRefreshEnabled = false
        try {
            val candles = AngelOneClient.fetchHistoricalCandles(
                symbolToken = "11536",
                symbol = "TCS"
            )
            assertNotNull(candles)
            assertTrue(candles.isEmpty(), "Should return an empty list when unauthenticated")
        } finally {
            AngelOneClient.autoRefreshEnabled = true
            // Restore correct client ID by logging back in (will use default credentials or env)
            AngelOneClient.login(clientId = originalClientId)
        }
    }

    @Test
    fun testPrintCurrentStrongSignals() {
        val originalClientId = AngelOneClient.activeClientId
        val success = AngelOneClient.login()
        if (!success) {
            println("FAILED TO LOGIN TO ANGEL ONE")
            return
        }
        try {
            var cacheFile = File("c:\\moba trade\\watchlist_intraday.json")
            if (!cacheFile.exists() || cacheFile.length() <= 2) {
                cacheFile = File("c:\\moba trade\\halal_stocks.json")
            }
            val content = cacheFile.readText(java.nio.charset.StandardCharsets.UTF_8)
            val array = org.json.JSONArray(content)
            val activeStocks = ArrayList<Triple<String, String, Double>>()
            val symbolToToken = mutableMapOf<String, String>()
            for (i in 0 until array.length()) {
                val obj = array.getJSONObject(i)
                val symbol = obj.optString("symbol").uppercase()
                val sector = obj.optString("sector", "IT").uppercase()
                val token = obj.optString("token", "")
                if (symbol.isNotEmpty() && token.isNotEmpty()) {
                    activeStocks.add(Triple(symbol, sector, 100.0))
                    symbolToToken[symbol] = token
                }
            }

            println("=== SCORING LIVE STOCKS FOR STRONG SIGNALS ===")
            for ((symbol, sector, _) in activeStocks) {
                val token = symbolToToken[symbol] ?: continue
                val candles = AngelOneClient.fetchHistoricalCandles(token, symbol, "FIFTEEN_MINUTE", 5)
                if (candles.isEmpty()) {
                    println("$symbol: Failed to fetch candles")
                    continue
                }
                val scorer = ConfluenceScorer(symbol, sector)
                val scored = scorer.scoreTrade(candles)
                if (scored.totalScore >= 3) {
                    println("🔥 STRONG SIGNAL: $symbol | Score = ${scored.totalScore} | Direction = ${scored.recommendedDirection} | Regime = ${scored.marketRegime} | SwingEligible = ${scored.isSwingEligible}")
                } else {
                    println("ℹ️ $symbol: Score = ${scored.totalScore} (Below threshold)")
                }
                // Sleep to avoid rate limiting
                try { Thread.sleep(500) } catch (e: InterruptedException) {}
            }
        } finally {
            // Restore correct client ID
            AngelOneClient.login(clientId = originalClientId)
        }
    }
}
